#include "Config.h"
#include <fstream>
#include <string>
#include <algorithm>
#include <sys/stat.h>
LPDConfig Config::values;
static bool b(const std::string& v){return v=="1"||v=="true"||v=="TRUE"||v=="on"||v=="ON";}
static std::string trim(std::string s){s.erase(s.begin(),std::find_if(s.begin(),s.end(),[](unsigned char c){return !std::isspace(c);}));s.erase(std::find_if(s.rbegin(),s.rend(),[](unsigned char c){return !std::isspace(c);}).base(),s.end());return s;}
const char* Config::Path(){return "/storage/emulated/0/Android_unprotected/data/com.rockstargames.gtasa/mods/configs/LuJimPassengerDriver.ini";}
void Config::EnsureDefault(){ mkdir("/storage/emulated/0/Android_unprotected/data/com.rockstargames.gtasa/mods",0777); mkdir("/storage/emulated/0/Android_unprotected/data/com.rockstargames.gtasa/mods/configs",0777); std::ifstream i(Path()); if(!i.good()) SaveEnabled(values.enabled); }
bool Config::Load(){ EnsureDefault(); std::ifstream f(Path()); if(!f.good()) return false; std::string line; while(std::getline(f,line)){line=trim(line); if(line.empty()||line[0]=='#'||line[0]==';'||line[0]=='[') continue; auto p=line.find('='); if(p==std::string::npos) continue; auto k=trim(line.substr(0,p)); auto v=trim(line.substr(p+1)); try{ if(k=="Enabled") values.enabled=b(v); else if(k=="HoldTime") values.holdTimeMs=std::max(500,std::stoi(v)); else if(k=="ShowNotifications") values.showNotifications=b(v); else if(k=="ShowProgressBar") values.showProgressBar=b(v); else if(k=="PlaySounds") values.playSounds=b(v); else if(k=="NotificationTime") values.notificationTimeMs=std::max(500,std::stoi(v)); else if(k=="RequireRecruit") values.requireRecruit=b(v); else if(k=="UseFirstRecruit") values.useFirstRecruit=b(v); else if(k=="UseNearestRecruit") values.useNearestRecruit=b(v); else if(k=="PatrolMode") values.patrolMode=b(v); else if(k=="RealisticEntry") values.realisticEntry=b(v); else if(k=="EnableLogs") values.enableLogs=b(v); else if(k=="ExperimentalHooks") values.experimentalHooks=b(v); }catch(...){}}
return true; }
bool Config::SaveEnabled(bool enabled){ values.enabled=enabled; EnsureDefault(); std::ofstream f(Path()); if(!f.good()) return false; f << "[LuJimPassengerDriver]\nEnabled="<<(values.enabled?1:0)<<"\nHoldTime="<<values.holdTimeMs<<"\nShowNotifications="<<(values.showNotifications?1:0)<<"\nShowProgressBar="<<(values.showProgressBar?1:0)<<"\nPlaySounds="<<(values.playSounds?1:0)<<"\nNotificationTime="<<values.notificationTimeMs<<"\nRequireRecruit="<<(values.requireRecruit?1:0)<<"\nUseFirstRecruit="<<(values.useFirstRecruit?1:0)<<"\nUseNearestRecruit="<<(values.useNearestRecruit?1:0)<<"\nPatrolMode="<<(values.patrolMode?1:0)<<"\nRealisticEntry="<<(values.realisticEntry?1:0)<<"\nEnableLogs="<<(values.enableLogs?1:0)<<"\nExperimentalHooks="<<(values.experimentalHooks?1:0)<<"\n\n[AllowedVehicles]\nCars=1\nPolice=1\nBikes=0\nBoats=0\nPlanes=0\nHelicopters=0\nCustomIDs=19001-19200\n\n[Compatibility]\nIgnoreMissionVehicles=1\nIgnoreOccupiedVehicles=1\nDisableDuringMissions=1\nDisableInCutscenes=1\n"; return true; }
